name = "Velexi"
uuid = "df234692-c8e6-4477-8353-992663219cfb"
repo = "https://github.com/velexi-research/JuliaRegistry.git"
description = "Velexi Julia Registry"

[packages]
4f49dcd8-3c92-4c49-9c92-5589c1fd49ac = { name = "XtallographyUtils", path = "X/XtallographyUtils" }
7adf08e9-5ce8-4ef7-b490-37ded1c6a328 = { name = "GeometricAlgebra", path = "G/GeometricAlgebra" }
